name: Deploy to gh-pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - uses: actions/setup-node@v2
          with:
            node-version: 16.x

        - run: yarn install


        - name: Deploy
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
            yarn build
            yarn gh-pages -d build -u "github-actions-bot <support+actions@github.com>"