name: Deploy to gh-pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: 16.x
            cache: 'npm'
        - run: yarn install
        - run: yarn deploy